kind: Secret
apiVersion: v1
metadata:
  name: gh-token
  namespace: demo-develop
  uid: 498c71b8-93fd-49fd-ad3a-aae5a6822fe1
  resourceVersion: '1890388'
  creationTimestamp: '2023-07-23T20:29:08Z'
  annotations:
    tekton.dev/git-0: 'https://github.com'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2023-07-23T20:29:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:password': {}
          'f:username': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:tekton.dev/git-0': {}
        'f:type': {}
data:
  password: Z2hwX2ltU2pjeHdhSkFQRDVZbjE0Zm9FOUJtNTE4Vno5MzJSODNtZg==
  username: dGFsLWhhc29u
type: kubernetes.io/basic-auth
