apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-cd
  namespace: openshift-gitops
spec:
  generators:
    - git:
        files:
          - path: Application/*/develop/values-*.yaml
        repoURL: 'http://gitea-http.gitea.svc/user1/user1-cd.git'
        revision: main
    - git:
        files:
          - path: Application/*/develop/values-*.yaml
        repoURL: 'http://gitea-http.gitea.svc/gothem/gothem-cd.git'
        revision: main
  template:
    metadata:
      name: '{{global.nameOverride}}-{{global.serviceName}}-{{path[2]}}'
    spec:
      destination:
        namespace: '{{global.nameOverride}}-{{path[2]}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        helm:
          valueFiles:
            - '{{path[1]}}/{{path[2]}}/{{path.filename}}'
        path: '{{path[0]}}'
        repoURL: >-
          http://gitea-http.gitea.svc/{{global.nameOverride}}/{{global.nameOverride}}-cd.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
status:
  conditions:
    - lastTransitionTime: '2023-09-06T19:19:32Z'
      message: Successfully generated parameters for all Applications
      reason: ApplicationSetUpToDate
      status: 'False'
      type: ErrorOccurred
    - lastTransitionTime: '2023-09-06T19:19:32Z'
      message: Successfully generated parameters for all Applications
      reason: ParametersGenerated
      status: 'True'
      type: ParametersGenerated
    - lastTransitionTime: '2023-09-06T19:19:32Z'
      message: ApplicationSet up to date
      reason: ApplicationSetUpToDate
      status: 'True'
      type: ResourcesUpToDate
