apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gotham-demo-developers-gh
  namespace: openshift-gitops
spec:
  generators:
    - scmProvider:
        filters:
          - repositoryMatch: gotham-cd
          - branchMatch: developer-*
        github:
          allBranches: true
          api: 'https://api.github.com/'
          organization: gotham-demo
          tokenRef:
            key: password
            secretName: repo-2837134776
  template:
    metadata:
      annotations:
        kargo.akuity.io/authorized-stage: 'gotham-kargo:{{branch}}'
      name: '{{ organization }}-{{ branch }}-gh'
    spec:
      destination:
        namespace: '{{organization}}-{{ branch }}'
        server: 'https://kubernetes.default.svc'
      project: gotham-gh
      sources:
        - helm:
            parameters:
              - name: global.namespace
                value: '{{branch}}'
            valueFiles:
              - gotham-demo/develop/values-batman.yaml
          path: Application
          repoURL: 'https://github.com/{{organization}}/{{repository}}.git'
          targetRevision: '{{branch}}'
        - helm:
            parameters:
              - name: global.namespace
                value: '{{branch}}'
            valueFiles:
              - gotham-demo/develop/values-joker.yaml
          path: Application
          repoURL: 'https://github.com/{{organization}}/{{repository}}.git'
          targetRevision: '{{branch}}'
        - helm:
            parameters:
              - name: global.namespace
                value: '{{branch}}'
            valueFiles:
              - gotham-demo/develop/values-robin.yaml
          path: Application
          repoURL: 'https://github.com/{{organization}}/{{repository}}.git'
          targetRevision: '{{branch}}'
        - helm:
            parameters:
              - name: global.namespace
                value: '{{branch}}'
            valueFiles:
              - gotham-demo/develop/values-riddler.yaml
          path: Application
          repoURL: 'https://github.com/{{organization}}/{{repository}}.git'
          targetRevision: '{{branch}}'
        - helm:
            parameters:
              - name: global.namespace
                value: '{{branch}}'
            valueFiles:
              - gotham-demo/develop/values-gotham.yaml
          path: Application
          repoURL: 'https://github.com/{{organization}}/{{repository}}.git'
          targetRevision: '{{branch}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

