apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gotham-demo-security-gh
  namespace: openshift-gitops
spec:
  generators:
    - git:
        files:
          - path: Application/*/develop/values-*.yaml
        repoURL: 'https://github.com/gotham-demo/gotham-cd.git'
        revision: main
  template:
    metadata:
      annotations:
        kargo.akuity.io/authorized-stage: 'gotham-kargo:develop'
      name: '{{global.nameOverride}}-{{global.serviceName}}-security'
    spec:
      destination:
        namespace: '{{global.nameOverride}}-{{path[2]}}'
        server: 'https://kubernetes.default.svc'
      project: gotham-gh
      source:
        helm:
          valueFiles:
            - '{{path[1]}}/{{path[2]}}/{{path.filename}}'
        path: '{{path[0]}}'
        repoURL: 'https://github.com/gotham-demo/{{global.nameOverride}}-cd.git'
        targetRevision: Deploy/Security
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

